my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from my_app import views


urlpatterns = [
    path("base/", views.BASE, name="base"),
    path('admin/', admin.site.urls),
    path('', views.Login, name='login'),
    path('role', views.Role, name='role'),

    path('admin-register/', views.School_Admin_Reg, name='admin_register'),
    path('parent/register/', views.Parent_Reg, name='parent_register'),
    path('admin-dashboard/', views.Admin_Dashboard, name='admin_dashboard'),
    path('employee-registration/', views.Employee_Reg, name='employee_registration'),
    path('employee-registration-sub-admin/', views.Employee_Reg_Sub_Admin, name='employee_registration_sub_admin'),
    path('sub-admin-register/', views.Sub_Admin_Reg, name='sub_admin_register'),
    path('sub-admin-dashboard/', views.Sub_Admin_Dashboard, name='sub_admin_dashboard'),
    path('assign-class_teacher/', views.Assign_Class_Teacher, name='assign_class_teacher'),
    path('view_all_sub_admins/', views.view_all_sub_admins, name='view_all_sub_admins'),
    path('delete_sub_admin/<int:id>/', views.delete_sub_admin, name='delete_sub_admin'),
    path('manage-employees/', views.Manage_Employees, name='manage_employees'),
    path('manage-teachers/', views.Manage_teachers, name='manage_teachers'),
    path('edit_teacher/<int:teacher_id>/', views.edit_teacher, name='edit_teacher'),
    path('delete_teacher/<int:teacher_id>/', views.delete_teacher, name='delete_teacher'),

    path('manage_students/', views.manage_students, name='manage_all_students'),
    path('manage_students/class/<str:class_assigned>/<str:division_assigned>/', views.class_students, name='class_students'),
    path('edit_student/<int:student_id>/', views.edit_student, name='edit_student'),
    path('delete_student/<int:student_id>/', views.delete_student, name='delete_student'),



    path('teacher/dashboard/', views.Teacher_Dashboard, name='teacher_dashboard'),
    path('teacher/manage-students/', views.Manage_Students, name='manage_students'),
    path('teacher/add-students/', views.Add_Students, name='add_students'),
    path('teacher/mark-students-attendance/', views.Mark_Student_Attendance, name='mark_attendance'),
    path('teacher/view-attedance-report/', views.View_Attendance_Report, name='view_attendance'),
    path('download_attendance_report_pdf/', views.Download_Attendance_Report_PDF, name='download_attendance_report_pdf'),

    path('select-date/', views.Select_Date, name='select_date'),
    path('teacher/manage-students/edit-attendance/', views.Edit_Attendance, name='edit_attendance'),
    path('view_student_all_marks/<int:student_id>/', views.view_student_all_marks, name='view_student_all_marks'),

    path('add_update_marks/', views.add_update_marks, name='add_update_marks'),
    path('create_exam/', views.create_exam, name='create_exam'),
    path('add_subjects/<int:exam_id>/', views.add_subjects, name='add_subjects'),
    path('enter_marks/<int:exam_id>/', views.enter_marks, name='enter_marks'),

    path('select_existing_exam/', views.select_existing_exam, name='select_existing_exam'),
    path('edit_marks/<int:exam_id>/', views.edit_marks, name='edit_marks'),

    path('view_student_marks/', views.view_student_marks, name='view_student_marks'),

    
]

my_project/my_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class School(models.Model):
    id = models.AutoField(primary_key=True)  # Explicit id field
    school_name = models.CharField(max_length=25)
    address = models.TextField()
    contact = models.CharField(max_length=15)
    school_admin_first_name = models.CharField(max_length=25, null=True)
    school_admin_last_name = models.CharField(max_length=25, null=True)
    school_admin_username = models.CharField(max_length=25, null=True)  # New field

    def __str__(self):
        return self.school_name

class Admin(models.Model):
    id = models.AutoField(primary_key=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    second_name = models.CharField(max_length=20)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=20, unique=True)
    contact_number = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.second_name} - {self.school}"

class Employee(models.Model):
    TEACHER = 'Teacher'
    PEON = 'Peon'
    SECURITY = 'Security'
    WARDEN = 'Warden'
    OFFICE_STAFF = 'Office Staff'

    DESIGNATION_CHOICES = [
        (TEACHER, 'Teacher'),
        (PEON, 'Peon'),
        (SECURITY, 'Security'),
        (WARDEN, 'Warden'),
        (OFFICE_STAFF, 'Office Staff'),
    ]

    id = models.AutoField(primary_key=True)  # Explicit id field
    school = models.ForeignKey(School, on_delete=models.CASCADE)  # Foreign key to School model
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Foreign key to User model
    user_name=models.CharField(max_length=25, null=True)
    first_name = models.CharField(max_length=25)
    second_name = models.CharField(max_length=25)
    contact_number = models.CharField(max_length=15)
    designation = models.CharField(
        max_length=20,
        choices=DESIGNATION_CHOICES,
        default=TEACHER,
    )

    def __str__(self):
        return f"{self.first_name} {self.second_name} - {self.designation} - {self.school}"
    

class Teacher(models.Model):
    id = models.AutoField(primary_key=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)  # Link to User model
    user_name = models.CharField(max_length=25, null=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    contact_number = models.CharField(max_length=15, null=True)
    is_class_teacher = models.BooleanField(default=False)  # New field

    def __str__(self):
        return f"{self.first_name} {self.last_name} - Teacher - {self.school}"
    

class Class_Teacher(models.Model):
    id = models.AutoField(primary_key=True)
    Teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)  # Ensure lowercase 'teacher'
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)  # Link to User model
    user_name = models.CharField(max_length=25, null=True)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    class_assigned = models.CharField(max_length=20)
    division_assigned = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.class_assigned} {self.division_assigned} - {self.school}"
    
class Warden(models.Model):
    id = models.AutoField(primary_key=True)  # Explicit id field
    school = models.ForeignKey(School, on_delete=models.CASCADE)  # Link to School model
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)  # Link to Employee model
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)  # Link to User model
    user_name = models.CharField(max_length=20, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    contact_number = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - Warden - {self.school}"
    


class Student(models.Model):
    id = models.AutoField(primary_key=True)  # Explicit id field
    school = models.ForeignKey(School, on_delete=models.CASCADE)  # Link to School
    class_teacher = models.ForeignKey(Class_Teacher, on_delete=models.CASCADE,null=True)  # Link to Class_Teacher
    warden = models.ForeignKey(Warden, on_delete=models.SET_NULL, null=True, blank=True)  
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=100,null=True)
    admission_number = models.CharField(max_length=20, null=True)
    roll_number = models.IntegerField(null=True)
    parents_number = models.CharField(max_length=15,null=True)
    parents_email=models.EmailField(max_length=40,null=True)
    class_assigned = models.CharField(max_length=20)
    division_assigned = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.roll_number} {self.first_name} {self.last_name} - {self.class_assigned} {self.division_assigned} - {self.school}"
    

class Attendance(models.Model):
    id = models.AutoField(primary_key=True)  # Explicit id field
    student = models.ForeignKey(Student, on_delete=models.CASCADE,null=True)
    date = models.DateField(default=date.today)
    is_present = models.BooleanField(default=False)  

    def __str__(self):
        return f"{self.student} - {'Absent' if not self.is_present else 'Present'} on {self.date}"
    

class Exam(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=20)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    class_assigned = models.CharField(max_length=20)
    division_assigned = models.CharField(max_length=10)
    exam_name = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.exam_name} - {self.class_assigned} {self.division_assigned} - {self.school}"

class Subject(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=25)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    class_assigned = models.CharField(max_length=20)
    division_assigned = models.CharField(max_length=10)
    subject_name = models.CharField(max_length=25)

    def __str__(self):
        return f"{self.subject_name} - {self.exam} - {self.school}"

class Marks(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    class_assigned = models.CharField(max_length=20)
    division_assigned = models.CharField(max_length=10)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    marks_obtained = models.CharField(max_length=10, null=True, blank=True)
    out_of = models.CharField(max_length=10, null=True, blank=True)
    date_uploaded = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.student} - {self.subject} - {self.exam} - {self.marks_obtained}/{self.out_of}"


class Hostel_Attendance(models.Model):
    id = models.AutoField(primary_key=True)  # Explicit id field
    student = models.ForeignKey(Student, on_delete=models.CASCADE,null=True)
    class_assigned = models.CharField(max_length=20)
    division_assigned = models.CharField(max_length=10)
    date = models.DateField(default=date.today)
    is_present = models.BooleanField(default=False)  

    def __str__(self):
        return f"{self.student} - {'Absent' if not self.is_present else 'Present'} on {self.date}"
    

my_project/templates/administrator/admin_dashboard.html
{% extends 'base.html' %}
{% block content %}
<h1>Admin dashboard</h1>
<a href="{% url 'employee_registration' %}">Register Employee</a><br>
<a href="{% url 'assign_class_teacher' %}">Assign Class Teacher</a><br>
<a href="{% url 'sub_admin_register' %}">Register Sub Admins</a><br>
<a href="{% url 'view_all_sub_admins' %}">View all sub admin</a><br>
<a href="{% url 'manage_employees' %}">Manage Employees</a><br>
<a href="{% url 'manage_all_students' %}">Manage Students</a>

{% endblock %}

my_project/templates/administrator/assign_class_teacher.html
{% extends 'base.html' %}
{% block content %}
<h1>Assign Class Teacher</h1>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <button type="submit">Assign</button>
</form>

<!-- JavaScript to auto-fill teacher details -->
<script>
$(document).ready(function() {
    $('#id_Teacher').select2({
        placeholder: 'Select a Teacher',
        allowClear: true
    });

    $('#id_Teacher').on('select2:select', function (e) {
        var selectedTeacher = e.params.data.text;
        var names = selectedTeacher.split(" - ")[0].split(" ");
        $('#id_first_name').val(names[0]);
        $('#id_last_name').val(names.slice(1).join(" "));
    });
});
</script>
{% endblock %}

my_project/templates/administrator/employee_registration.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'admin_dashboard' %}">Back</a>
<h2>Employee Registration</h2>

{% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}

my_project/templates/administrator/sub_admin_register.html
{% extends 'base.html' %}
{% block content %}
<h1>Register Sub Admin</h1>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form method="POST">
    {% csrf_token %}
    <div>
        <label for="username">Username:</label>
        <input type="text" name="username" id="username" required>
    </div>
    <div>
        <label for="password">Password:</label>
        <input type="password" name="password" id="password" required>
    </div>
    <div>
        <label for="confirm_password">Confirm Password:</label>
        <input type="password" name="confirm_password" id="confirm_password" required>
    </div>
    <div>
        <label for="sub_admin_first_name">Sub Admin First Name:</label>
        <input type="text" name="sub_admin_first_name" id="sub_admin_first_name" required>
    </div>
    <div>
        <label for="sub_admin_last_name">Sub Admin Last Name:</label>
        <input type="text" name="sub_admin_last_name" id="sub_admin_last_name" required>
    </div>
    <div>
        <label for="sub_admin_school">School:</label>
        <select name="sub_admin_school" id="sub_admin_school" required>
            {% for school in form.fields.sub_admin_school.queryset %}
                <option value="{{ school.id }}" {% if school.id == form.fields.sub_admin_school.initial.id %}selected{% endif %}>{{ school.school_name }}</option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for="contact_number">Contact Number:</label>
        <input type="text" name="contact_number" id="contact_number" required>
    </div>
    <button type="submit">Register</button>
</form>
{% endblock %}